feat(ADM-1380): Upgrade harvest-client To Use Java17
3AP-AG/harvest-client pull request #16
Opened 2021-10-21 10:47 UTC by PredragMPetrovic

### Checklist

- [x] I've run `./gradlew test` from the root directory to see all new and existing tests pass
- [x] I've followed the _harvest-client_ code style
- [x] I've read the [Contribution Guidelines][contribution guidelines]
- [x] I've updated the documentation if necessary.

### Motivation and Context

Motivation is to use the latest version of Java
I tested it with running 'gradle build' and './gradlew test' locally

### Description

- project is set to use Java17 from openjdk
- gradle version is bumped to 7.2
- jacoco version is bumped to 0.8.7

[contribution guidelines]: ../CONTRIBUTING.md

2021-10-22 09:02 UTC, primaproxima approved these changes
@mnembrini Does this look good to you? I am clueless.
Approving since @PredragMPetrovic stated he tested locally.

2021-10-26 11:40 UTC, mmilic90 reviewed
I tried out locally but build and test failed. If there is something else I can do to test this out, we can exchange what else can be done.

2021-10-26 13:21 UTC, mmilic90 approved these changes

2021-10-26 13:29 UTC, mnembrini requested changes

2021-10-27 06:52 UTC, mnembrini approved these changes
Looks good now 👍

2021-10-27 06:52 UTC, merged